baseURL = "https://clubrobot.github.io/website/"
languageCode = "fr-fr"
title = "Club Robot Insa Rennes"
theme = "ananke"
MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 8 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
RelativeURLs=true
CanonifyURLs=true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  logo = "https://clubrobot.github.io/website/images/logo_blanc.png"
  description = "Equipe de robotique"
  facebook = "https://www.facebook.com/clubrobot/"
  twitter = ""
  youtube = "https://www.youtube.com/channel/UClb8TbQc3atbJL6qw8v9fhw"
  github = "https://github.com/clubrobot"
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-white"
  recent_posts_number = 5
